# Float Steam, fullscreen RetroArch
windowrule = float on, match:class fork
windowrule = center on, match:class fork, match:title Fork
windowrule = opacity 1 1, match:class fork
windowrule = size 1100 700, match:class fork, match:title Fork
windowrule = idle_inhibit fullscreen, match:class fork
