windowrule {
  name = fork-general
  match:class = fork.exe
  float = on
  opacity = 1 1
  idle_inhibit = fullscreen
}

windowrule {
    name = fork-sized-centered
    match:class = fork.exe
    match:title = Fork
    center = on
    size = 1500 850
}
