# Fixing popup size issue
# windowrule = size 50% 50%, match:class:(.*jetbrains.*)$, match:title:^$,floating:1

windowrule = min_size (monitor_w*0.5) (monitor_h*0.5), match:class jetbrains-toolbox match:title ^$, match:float 1

# Fix tab dragging (always have a single space character as their title)
windowrule = tile on, match:class ^(.*jetbrains.*)$, match:title ^\\s$
windowrule = no_initial_focus on, match:class ^(.*jetbrains.*)$, match:title ^\\s$

windowrule = no_initial_focus on, match:class ^(.*jetbrains.*)$, match:title ^(win.*)$

windowrule = workspace 4 silent, match:class ^(.*jetbrains.*)$, match:title ^\\s$

windowrule = opacity 1.0 1.0, match:class ^(.*jetbrains.*)$
