# Float Steam, fullscreen RetroArch
windowrule = float on, match:class unityhub
windowrule = center on, match:class unityhub, match:title Unity Hub
windowrule = opacity 1 1, match:class unityhub
windowrule = size 1100 700, match:class unityhub, match:title Unity Hub
windowrule = idle_inhibit fullscreen, match:class unityhub

# windowrule = workspace 3, class:Unity, title:^(Unity*)$
windowrule = workspace 3 silent, match:class (Unity), match:title .*Unity.*
windowrule = no_initial_focus on, match:class (Unity), match:title .*Unity.*
