# For Unity Editor / project windows (using regex for flexible title matching)
windowrule {
    name = unity-editor-workspace
    match:class = ^(Unity)$
    match:title = .*Unity.*
    workspace = 3 silent
}

windowrule {
    name = unity-editor-no-focus
    match:class = ^(Unity)$
    match:title = .*Unity.*
    no_initial_focus = on
}

windowrule {
  name = unityhub-general
  match:class = unityhub
  float = on
  opacity = 1 1
  idle_inhibit = fullscreen
}

windowrule {
    name = unityhub-sized-centered
    match:class = unityhub
    match:title = .*Unity.*
    center = on
    size = 1500 850
}
