#!/bin/bash

sudo pacman -S --noconfirm --needed \
  alacritty \
  avahi \
  bash-completion \
  bat \
  blueberry \
  brightnessctl \
  btop \
  cups \
  cups-browsed \
  cups-filters \
  cups-pdf \
  dust \
  elephant \
  elephant-bluetooth \
  elephant-calc \
  elephant-clipboard \
  elephant-desktopapplications \
  elephant-files \
  elephant-menus \
  elephant-providerlist \
  elephant-runner \
  elephant-symbols \
  elephant-todo \
  elephant-unicode \
  elephant-websearch \
  evince \
  eza \
  fastfetch \
  fcitx5 \
  fcitx5-gtk \
  fcitx5-qt \
  fd \
  fzf \
  gnome-keyring \
  gnome-themes-extra \
  gpu-screen-recorder \
  gum \
  hypridle \
  hyprland \
  hyprland-qtutils \
  hyprlock \
  hyprpicker \
  hyprsunset \
  imagemagick \
  imv \
  inetutils \
  iwd \
  kvantum-qt5 \
  lazygit \
  less \
  libqalculate \
  llvm \
  mako \
  man \
  mise \
  mpv \
  nautilus \
  noto-fonts \
  noto-fonts-cjk \
  noto-fonts-emoji \
  noto-fonts-extra \
  nss-mdns \
  chromium \
  pamixer \
  plocate \
  plymouth \
  polkit-gnome \
  power-profiles-daemon \
  python-gobject \
  python-poetry-core \
  python-terminaltexteffects \
  qt5-wayland \
  ripgrep \
  satty \
  slurp \
  starship \
  sushi \
  swaybg \
  swayosd \
  system-config-printer \
  tldr \
  ttf-cascadia-mono-nerd \
  ttf-ia-writer \
  ttf-jetbrains-mono-nerd \
  tzupdate \
  ufw \
  unzip \
  uwsm \
  walker-bin \
  waybar \
  whois \
  wiremix \
  wireplumber \
  wl-clipboard \
  woff2-font-awesome \
  xdg-desktop-portal-gtk \
  xdg-desktop-portal-hyprland \
  yaru-icon-theme \
  yay \
  zoxide

sudo pacman -Sy --noconfirm --needed \
  helix network-manager-sstp wine

